In [1]:
import numpy as np
import pandas as pd
import torch
import transformers
import datasets

print("NumPy:", np.__version__)
print("Pandas:", pd.__version__)
print("PyTorch:", torch.__version__)
print("Transformers:", transformers.__version__)
print("Datasets:", datasets.__version__)

NumPy: 2.5.2
Pandas: 3.0.5
PyTorch: 2.13.0+cpu
Transformers: 5.15.1
Datasets: 5.0.1

In [3]:
from datasets import load_dataset

dataset = load_dataset("stanfordnlp/imdb")

print(dataset)

README.md:   0%|          | 0.00/7.81k [00:00<?, ?B/s]

c:\Users\prasanna kumari\OneDrive\Desktop\AI-Movie-Review-Sentiment-Analysis\venv\Lib\site-packages\huggingface_hub\file_download.py:141: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\prasanna kumari\.cache\huggingface\hub\datasets--stanfordnlp--imdb. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

plain_text/train-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 21.0MB

plain_text/train-00000-of-00001.parquet: downloading bytes:           |  0.00B

plain_text/test-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 20.5MB

plain_text/test-00000-of-00001.parquet: downloading bytes:           |  0.00B

plain_text/unsupervised-00000-of-00001.p(…): reconstructing file:   0%|          |  0.00B / 42.0MB

plain_text/unsupervised-00000-of-00001.p(…): downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating unsupervised split:   0%|          | 0/50000 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    unsupervised: Dataset({
        features: ['text', 'label'],
        num_rows: 50000
    })
})

In [4]:
print(dataset["train"][0])

{'text': 'I rented I AM CURIOUS-YELLOW from my video store because of all the controversy that surrounded it when it was first released in 1967. I also heard that at first it was seized by U.S. customs if it ever tried to enter this country, therefore being a fan of films considered "controversial" I really had to see this for myself.<br /><br />The plot is centered around a young Swedish drama student named Lena who wants to learn everything she can about life. In particular she wants to focus her attentions to making some sort of documentary on what the average Swede thought about certain political issues such as the Vietnam War and race issues in the United States. In between asking politicians and ordinary denizens of Stockholm about their opinions on politics, she has sex with her drama teacher, classmates, and married men.<br /><br />What kills me about I AM CURIOUS-YELLOW is that 40 years ago, this was considered pornographic. Really, the sex and nudity scenes are few and far between, even then it\'s not shot like some cheaply made porno. While my countrymen mind find it shocking, in reality sex and nudity are a major staple in Swedish cinema. Even Ingmar Bergman, arguably their answer to good old boy John Ford, had sex scenes in his films.<br /><br />I do commend the filmmakers for the fact that any sex shown in the film is shown for artistic purposes rather than just to shock people and make money to be shown in pornographic theaters in America. I AM CURIOUS-YELLOW is a good film for anyone wanting to study the meat and potatoes (no pun intended) of Swedish cinema. But really, this film doesn\'t have much of a plot.', 'label': 0}

In [6]:
print(dataset["train"][1])

{'text': '"I Am Curious: Yellow" is a risible and pretentious steaming pile. It doesn\'t matter what one\'s political views are because this film can hardly be taken seriously on any level. As for the claim that frontal male nudity is an automatic NC-17, that isn\'t true. I\'ve seen R-rated films with male nudity. Granted, they only offer some fleeting views, but where are the R-rated films with gaping vulvas and flapping labia? Nowhere, because they don\'t exist. The same goes for those crappy cable shows: schlongs swinging in the breeze but not a clitoris in sight. And those pretentious indie movies like The Brown Bunny, in which we\'re treated to the site of Vincent Gallo\'s throbbing johnson, but not a trace of pink visible on Chloe Sevigny. Before crying (or implying) "double-standard" in matters of nudity, the mentally obtuse should take into account one unavoidably obvious anatomical difference between men and women: there are no genitals on display when actresses appears nude, and the same cannot be said for a man. In fact, you generally won\'t see female genitals in an American film in anything short of porn or explicit erotica. This alleged double-standard is less a double standard than an admittedly depressing ability to come to terms culturally with the insides of women\'s bodies.', 'label': 0}

In [7]:
print(dataset["train"].features)

{'text': Value('string'), 'label': ClassLabel(names=['neg', 'pos'])}

In [8]:
train_data = dataset["train"]
test_data = dataset["test"]

print("Training samples:", len(train_data))
print("Testing samples:", len(test_data))

Training samples: 25000
Testing samples: 25000

In [9]:
from collections import Counter

print(Counter(train_data["label"]))

Counter({0: 12500, 1: 12500})

In [10]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

print("Tokenizer loaded successfully!")

config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

c:\Users\prasanna kumari\OneDrive\Desktop\AI-Movie-Review-Sentiment-Analysis\venv\Lib\site-packages\huggingface_hub\file_download.py:141: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\prasanna kumari\.cache\huggingface\hub\models--distilbert-base-uncased. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

Tokenizer loaded successfully!

In [11]:
text = train_data[0]["text"]

tokens = tokenizer(
    text,
    truncation=True,
    padding="max_length",
    max_length=128
)

print(tokens.keys())
print("Input IDs:", tokens["input_ids"][:20])
print("Attention Mask:", tokens["attention_mask"][:20])

KeysView({'input_ids': [101, 1045, 12524, 1045, 2572, 8025, 1011, 3756, 2013, 2026, 2678, 3573, 2138, 1997, 2035, 1996, 6704, 2008, 5129, 2009, 2043, 2009, 2001, 2034, 2207, 1999, 3476, 1012, 1045, 2036, 2657, 2008, 2012, 2034, 2009, 2001, 8243, 2011, 1057, 1012, 1055, 1012, 8205, 2065, 2009, 2412, 2699, 2000, 4607, 2023, 2406, 1010, 3568, 2108, 1037, 5470, 1997, 3152, 2641, 1000, 6801, 1000, 1045, 2428, 2018, 2000, 2156, 2023, 2005, 2870, 1012, 1026, 7987, 1013, 1028, 1026, 7987, 1013, 1028, 1996, 5436, 2003, 8857, 2105, 1037, 2402, 4467, 3689, 3076, 2315, 14229, 2040, 4122, 2000, 4553, 2673, 2016, 2064, 2055, 2166, 1012, 1999, 3327, 2016, 4122, 2000, 3579, 2014, 3086, 2015, 2000, 2437, 2070, 4066, 1997, 4516, 2006, 2054, 1996, 2779, 25430, 14728, 2245, 2055, 3056, 2576, 3314, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]})
Input IDs: [101, 1045, 12524, 1045, 2572, 8025, 1011, 3756, 2013, 2026, 2678, 3573, 2138, 1997, 2035, 1996, 6704, 2008, 5129, 2009]
Attention Mask: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [12]:
def tokenize_function(examples):
    return tokenizer(
        examples["text"],
        truncation=True,
        padding="max_length",
        max_length=128
    )

tokenized_train = train_data.map(tokenize_function, batched=True)
tokenized_test = test_data.map(tokenize_function, batched=True)

print(tokenized_train)
print(tokenized_test)

Map:   0%|          | 0/25000 [00:00<?, ? examples/s]

Map:   0%|          | 0/25000 [00:00<?, ? examples/s]

Dataset({
    features: ['text', 'label', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 25000
})
Dataset({
    features: ['text', 'label', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 25000
})

In [13]:
from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=2
)

print("Model loaded successfully!")

model.safetensors: reconstructing file:   0%|          |  0.00B /  268MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |
pre_classifier.weight   | MISSING    |
pre_classifier.bias     | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Model loaded successfully!

In [14]:
print("Device:", next(model.parameters()).device)

Device: cpu

In [15]:
small_train = tokenized_train.select(range(2000))
small_test = tokenized_test.select(range(500))

print("Small training dataset:", len(small_train))
print("Small testing dataset:", len(small_test))

Small training dataset: 2000
Small testing dataset: 500

In [1]:
from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./models/distilbert-sentiment",
    num_train_epochs=1,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    logging_steps=50,
    save_strategy="no",
    report_to="none"
)

print("Training configuration created successfully!")

Training configuration created successfully!

In [12]:
from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=small_train,
    eval_dataset=small_test
)

print("Trainer created successfully!")

Trainer created successfully!

In [3]:
from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=2
)

print("Model loaded successfully!")

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
classifier.weight       | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |
pre_classifier.bias     | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Model loaded successfully!

In [11]:
small_train = tokenized_train.select(range(2000))
small_test = tokenized_test.select(range(500))

print("Small training dataset:", len(small_train))
print("Small testing dataset:", len(small_test))

Small training dataset: 2000
Small testing dataset: 500

In [8]:
from datasets import load_dataset

dataset = load_dataset("stanfordnlp/imdb")

print(dataset)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    unsupervised: Dataset({
        features: ['text', 'label'],
        num_rows: 50000
    })
})

In [9]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

print("Tokenizer loaded successfully!")

Tokenizer loaded successfully!

In [10]:
def tokenize_function(examples):
    return tokenizer(
        examples["text"],
        truncation=True,
        padding="max_length",
        max_length=128
    )

tokenized_train = dataset["train"].map(tokenize_function, batched=True)
tokenized_test = dataset["test"].map(tokenize_function, batched=True)

print("Training samples:", len(tokenized_train))
print("Testing samples:", len(tokenized_test))

Training samples: 25000
Testing samples: 25000

In [13]:
train_result = trainer.train()

print("Training completed successfully!")

c:\Users\prasanna kumari\OneDrive\Desktop\AI-Movie-Review-Sentiment-Analysis\venv\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Training completed successfully!

In [14]:
from sklearn.metrics import accuracy_score
import numpy as np

predictions = trainer.predict(small_test)

pred_labels = np.argmax(predictions.predictions, axis=-1)

accuracy = accuracy_score(small_test["label"], pred_labels)

print("Test Accuracy:", accuracy)
print("Test Accuracy (%):", accuracy * 100)

Test Accuracy: 1.0
Test Accuracy (%): 100.0

In [17]:
review = "The movie was absolutely fantastic. The acting was brilliant and I really enjoyed every moment."

inputs = tokenizer(
    review,
    return_tensors="pt",
    truncation=True,
    padding=True,
    max_length=128
)

with torch.no_grad():
    outputs = model(**inputs)

prediction = torch.argmax(outputs.logits, dim=1).item()

if prediction == 1:
    print("Sentiment: POSITIVE 😊")
else:
    print("Sentiment: NEGATIVE 😞")

Sentiment: NEGATIVE 😞

In [16]:
import torch

In [18]:
import torch

review = "The movie was absolutely fantastic. The acting was brilliant and I really enjoyed every moment."

inputs = tokenizer(
    review,
    return_tensors="pt",
    truncation=True,
    padding=True,
    max_length=128
)

with torch.no_grad():
    outputs = model(**inputs)

probabilities = torch.softmax(outputs.logits, dim=1)

print("Negative probability:", probabilities[0][0].item())
print("Positive probability:", probabilities[0][1].item())

Negative probability: 0.9998986721038818
Positive probability: 0.00010132647003047168

In [19]:
review = "This movie was terrible. The story was boring, the acting was awful, and I hated it."

inputs = tokenizer(
    review,
    return_tensors="pt",
    truncation=True,
    padding=True,
    max_length=128
)

with torch.no_grad():
    outputs = model(**inputs)

probabilities = torch.softmax(outputs.logits, dim=1)

print("Negative probability:", probabilities[0][0].item())
print("Positive probability:", probabilities[0][1].item())

Negative probability: 0.9999033212661743
Positive probability: 9.666231198934838e-05

In [20]:
import numpy as np

predictions = trainer.predict(small_test)
pred_labels = np.argmax(predictions.predictions, axis=-1)

print("Negative predictions:", np.sum(pred_labels == 0))
print("Positive predictions:", np.sum(pred_labels == 1))

c:\Users\prasanna kumari\OneDrive\Desktop\AI-Movie-Review-Sentiment-Analysis\venv\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Negative predictions: 500
Positive predictions: 0

In [21]:
from collections import Counter

print(Counter(tokenized_train["label"]))

Counter({0: 12500, 1: 12500})

In [22]:
train_data_10k = tokenized_train.select(range(10000))
test_data_2k = tokenized_test.select(range(2000))

print("Training samples:", len(train_data_10k))
print("Testing samples:", len(test_data_2k))

Training samples: 10000
Testing samples: 2000

In [23]:
from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./models/distilbert-sentiment",
    num_train_epochs=1,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    logging_steps=100,
    save_strategy="no",
    report_to="none"
)

print("New training configuration created successfully!")

New training configuration created successfully!

In [24]:
from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_data_10k,
    eval_dataset=test_data_2k
)

print("New Trainer created successfully!")

New Trainer created successfully!

In [25]:
train_result = trainer.train()

print("Training completed successfully!")

Training completed successfully!

In [26]:
predictions = trainer.predict(test_data_2k)

pred_labels = np.argmax(predictions.predictions, axis=-1)

accuracy = accuracy_score(test_data_2k["label"], pred_labels)

print("Test Accuracy:", accuracy)
print("Test Accuracy (%):", accuracy * 100)

print("Negative predictions:", np.sum(pred_labels == 0))
print("Positive predictions:", np.sum(pred_labels == 1))

Test Accuracy: 1.0
Test Accuracy (%): 100.0
Negative predictions: 2000
Positive predictions: 0

In [27]:
from collections import Counter

print(Counter(test_data_2k["label"]))

Counter({0: 2000})

In [30]:
negative_test = tokenized_test.filter(lambda x: x["label"] == 0).select(range(1000))
positive_test = tokenized_test.filter(lambda x: x["label"] == 1).select(range(1000))

test_data_balanced = concatenate_datasets([
    negative_test,
    positive_test
])

print("Test samples:", len(test_data_balanced))
print("Test labels:", Counter(test_data_balanced["label"]))

Test samples: 2000
Test labels: Counter({0: 1000, 1: 1000})

In [29]:
from datasets import concatenate_datasets

print("Import successful!")

Import successful!

In [31]:
predictions = trainer.predict(test_data_balanced)

pred_labels = np.argmax(predictions.predictions, axis=-1)

accuracy = accuracy_score(
    test_data_balanced["label"],
    pred_labels
)

print("Test Accuracy:", accuracy)
print("Test Accuracy (%):", accuracy * 100)

print("Negative predictions:", np.sum(pred_labels == 0))
print("Positive predictions:", np.sum(pred_labels == 1))

c:\Users\prasanna kumari\OneDrive\Desktop\AI-Movie-Review-Sentiment-Analysis\venv\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Test Accuracy: 0.5
Test Accuracy (%): 50.0
Negative predictions: 2000
Positive predictions: 0

In [32]:
print(train_data_10k[0])

{'text': 'I rented I AM CURIOUS-YELLOW from my video store because of all the controversy that surrounded it when it was first released in 1967. I also heard that at first it was seized by U.S. customs if it ever tried to enter this country, therefore being a fan of films considered "controversial" I really had to see this for myself.<br /><br />The plot is centered around a young Swedish drama student named Lena who wants to learn everything she can about life. In particular she wants to focus her attentions to making some sort of documentary on what the average Swede thought about certain political issues such as the Vietnam War and race issues in the United States. In between asking politicians and ordinary denizens of Stockholm about their opinions on politics, she has sex with her drama teacher, classmates, and married men.<br /><br />What kills me about I AM CURIOUS-YELLOW is that 40 years ago, this was considered pornographic. Really, the sex and nudity scenes are few and far between, even then it\'s not shot like some cheaply made porno. While my countrymen mind find it shocking, in reality sex and nudity are a major staple in Swedish cinema. Even Ingmar Bergman, arguably their answer to good old boy John Ford, had sex scenes in his films.<br /><br />I do commend the filmmakers for the fact that any sex shown in the film is shown for artistic purposes rather than just to shock people and make money to be shown in pornographic theaters in America. I AM CURIOUS-YELLOW is a good film for anyone wanting to study the meat and potatoes (no pun intended) of Swedish cinema. But really, this film doesn\'t have much of a plot.', 'label': 0, 'input_ids': [101, 1045, 12524, 1045, 2572, 8025, 1011, 3756, 2013, 2026, 2678, 3573, 2138, 1997, 2035, 1996, 6704, 2008, 5129, 2009, 2043, 2009, 2001, 2034, 2207, 1999, 3476, 1012, 1045, 2036, 2657, 2008, 2012, 2034, 2009, 2001, 8243, 2011, 1057, 1012, 1055, 1012, 8205, 2065, 2009, 2412, 2699, 2000, 4607, 2023, 2406, 1010, 3568, 2108, 1037, 5470, 1997, 3152, 2641, 1000, 6801, 1000, 1045, 2428, 2018, 2000, 2156, 2023, 2005, 2870, 1012, 1026, 7987, 1013, 1028, 1026, 7987, 1013, 1028, 1996, 5436, 2003, 8857, 2105, 1037, 2402, 4467, 3689, 3076, 2315, 14229, 2040, 4122, 2000, 4553, 2673, 2016, 2064, 2055, 2166, 1012, 1999, 3327, 2016, 4122, 2000, 3579, 2014, 3086, 2015, 2000, 2437, 2070, 4066, 1997, 4516, 2006, 2054, 1996, 2779, 25430, 14728, 2245, 2055, 3056, 2576, 3314, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [33]:
from collections import Counter

print("Training labels:", Counter(train_data_10k["label"]))
print("Negative:", train_data_10k["label"].count(0))
print("Positive:", train_data_10k["label"].count(1))

Training labels: Counter({0: 10000})
Negative: 10000
Positive: 0

In [34]:
negative_train = tokenized_train.filter(lambda x: x["label"] == 0).select(range(5000))
positive_train = tokenized_train.filter(lambda x: x["label"] == 1).select(range(5000))

train_data_balanced = concatenate_datasets([
    negative_train,
    positive_train
])

print("Training samples:", len(train_data_balanced))
print("Training labels:", Counter(train_data_balanced["label"]))

Filter:   0%|          | 0/25000 [00:00<?, ? examples/s]

Filter:   0%|          | 0/25000 [00:00<?, ? examples/s]

Training samples: 10000
Training labels: Counter({0: 5000, 1: 5000})

In [35]:
from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=2
)

print("Fresh model loaded successfully!")

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
classifier.weight       | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |
pre_classifier.bias     | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Fresh model loaded successfully!

In [36]:
from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_data_balanced,
    eval_dataset=test_data_balanced
)

print("Trainer created successfully!")

Trainer created successfully!

In [37]:
train_result = trainer.train()

print("Training completed successfully!")

c:\Users\prasanna kumari\OneDrive\Desktop\AI-Movie-Review-Sentiment-Analysis\venv\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Training completed successfully!

In [38]:
predictions = trainer.predict(test_data_balanced)

pred_labels = np.argmax(predictions.predictions, axis=-1)

accuracy = accuracy_score(
    test_data_balanced["label"],
    pred_labels
)

print("Test Accuracy:", accuracy)
print("Test Accuracy (%):", accuracy * 100)

print("Negative predictions:", np.sum(pred_labels == 0))
print("Positive predictions:", np.sum(pred_labels == 1))

Test Accuracy: 0.8505
Test Accuracy (%): 85.05
Negative predictions: 981
Positive predictions: 1019

In [39]:
import torch

def predict_sentiment(text):
    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        padding=True,
        max_length=128
    )

    with torch.no_grad():
        outputs = model(**inputs)

    probabilities = torch.softmax(outputs.logits, dim=-1)
    prediction = torch.argmax(probabilities, dim=-1).item()

    if prediction == 1:
        sentiment = "Positive"
    else:
        sentiment = "Negative"

    confidence = probabilities[0][prediction].item() * 100

    print("Review:", text)
    print("Sentiment:", sentiment)
    print("Confidence:", round(confidence, 2), "%")


predict_sentiment(
    "The movie was absolutely fantastic. The acting was brilliant and I really enjoyed every moment."
)

Review: The movie was absolutely fantastic. The acting was brilliant and I really enjoyed every moment.
Sentiment: Positive
Confidence: 98.92 %

In [40]:
predict_sentiment(
    "The movie was terrible. The acting was poor, the story was boring, and I really disliked it."
)

Review: The movie was terrible. The acting was poor, the story was boring, and I really disliked it.
Sentiment: Negative
Confidence: 99.13 %

In [41]:
trainer.save_model("./models/distilbert-sentiment")
tokenizer.save_pretrained("./models/distilbert-sentiment")

print("Model and tokenizer saved successfully!")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model and tokenizer saved successfully!

In [42]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

saved_path = "./models/distilbert-sentiment"

loaded_tokenizer = AutoTokenizer.from_pretrained(saved_path)
loaded_model = AutoModelForSequenceClassification.from_pretrained(saved_path)

print("Saved model loaded successfully!")
print("Model type:", type(loaded_model).__name__)

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

Saved model loaded successfully!
Model type: DistilBertForSequenceClassification